---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n-helm
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: 1.0.10
