---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgres-helm
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: 16.7.27
