apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {
        admin off
        servers {
            trusted_proxies static 10.0.0.44
        }
    }

    :80 {
        root * /var/www/html/public
        encode gzip

      php_fastcgi unix//run/php/php8.4-fpm.sock {
          root /var/www/html/public
          index index.php

          env PHP_VALUE "upload_max_filesize = 100M
          post_max_size = 100M"
          env HTTP_PROXY ""
          env HTTPS "on"

          read_timeout 300s
          dial_timeout 300s
          write_timeout 300s

          file_server
      }

      header Strict-Transport-Security "max-age=16768000; preload;"
      header X-Content-Type-Options "nosniff"
      header X-XSS-Protection "1; mode=block;"
      header X-Robots-Tag "none"
      header Content-Security-Policy "frame-ancestors 'self'"
      header X-Frame-Options "DENY"
      header Referrer-Policy "same-origin"

      request_body {
          max_size 100m
      }
    }
