apiVersion: v1
kind: Service
metadata:
  name: pelican-panel
spec:
  type: LoadBalancer
  selector:
    app: pelican-panel
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
