---
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.15.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - kind: Secret
      name: grafana-login
      valuesKey: values.yaml
  values:
    alertmanger:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - alertmanger.endsys.cloud
        paths:
          - /
    grafana:
      enabled: true
      defaultDashboardsTimezone: browsers
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - grafana.endsys.cloud
        path: /
    prometheus:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - prometheus.endsys.cloud
        paths:
          - /