# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:CPumGBpxv6G9Q9Iw0EM0sWZ3XfFmbSURn/ECz5R/3v+FZr+FHGYsY+84SkMiuWB+vKdkz1nTZgOB5G9nVKu1mVF4asTK50p1jTZ+0yzXmBx1N77iiAUZ9FzViFqDDwOCi5y+XIUa+9WbyXHQ1XL5PmL1lpXaW1eaMHAY9aCkoPpFbJammcE/+17igVrRu1fVa7I8ZMLiZTX6JGFwOGGX6uNo5xhGAJdNInabdpTUqg==,iv:8eS2Jf1nPs/qVu2xgzfQtetnqIWWLS8rRVEPDAAwB+0=,tag:o49Qq8FeSEh7IFxkt40YyA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d3dFWEk2eldzMEN5dTZM
        Q0JqVkhCaHBCZThKQzBwTDlDb3pNcC9QSlVJClFXUWFoTWZ6MXFtWFQ2QU9YMzBm
        emNpRUc1OHZBdE42WWFIR3F1bzJUOWcKLS0tIDUrNk90Q1IzS00wUTZzck9kcjIw
        WDQvSGRoblV3K0RaT2xlM0pYb0d2dEEKqLtO1ukeCo1Pr+ggnasgWx8cCMzrddnh
        i+LRiYvwR3dJdTTqcJ56gzUFle+kIvK9ZGWFqQhIRFHKXFfWNcDKGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-28T15:39:50Z"
  mac: ENC[AES256_GCM,data:l79Y1T/GKpTJP92qkMOaWY1UW0q6Dzy0zlfRq6ELzV+bFhF/JJx4wwsJvCouALuUSvq5yefaLVEt0KxKzEv/tx5/EFKF+AF0Uq/CXNvtNY324RdzkEUzj0XrrKgSGIdnB9nlFJLnJ9kvRb6kYvqfP4ynQAEOyf43epBnHh5wWNQ=,iv:gmNimke6bFRel1SohfS3y9M6DtMgjA5te3w94EZAfWM=,tag:rZ1iK/jtGN6z5vt3rHObWg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
