# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:109WAKwts8iMZd6K6Vu9ZKAmIAuh6vIamdyk93zv6Um2Qx5ABruFxpGlG8YUoV0oKpUls/FDTdzcQHJCahVVEtRPN9kOV37cVHDzdJgPO3m0sbMgSGdSN3SH1R1kXLeYIM5zdrT3I/K0D/Z+6zvnusXaFtQevraXNaSjwuC46BwDIglNfzlOrU4Apiit5Tll8YGGM7YZoF97r7YB31HY+eFCTwIHckfQDxUO8Km9mA==,iv:NhMowH7/o3MfK1PAtLev8RyhFe7GZxDvoaBT0ZM/eHE=,tag:02odIrJvhVmKloTIXvqO9A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOXZmSlRVM0R2ZjhVcVgr
        cmd1NzR5MFlwRUNuS3JNU3FPM25CWnJSQW00CjZoQ0dHRlArejh2eG03Rm13Ymxj
        Qm1nZ3BtMzBtVFFadmRBOFNsdzRCb2MKLS0tIHFWQVE2dXArVitoY20vRUdRVWdS
        VUZTV0VLU1FtZFpTWHJJbk9UY2EydE0KOd6HJxYBNBcp+oX11fJykkD4cbJA6kRM
        KQu0IsroRRUEKksNw/T09dm3aTp/10IGzwcpryNijPDxPwIAlAhWqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T15:28:16Z"
  mac: ENC[AES256_GCM,data:5MpDxnTNrqbWmoR/gCFCmzdJjhClrP5HPu8FnhsjfjTM3HRwBbgVWDoyZdQXNKEhcpo7C6VyRm1OhyrwWjUQjniWmKMPtFnXxe0C7Oft/SWnODqG37zfZ+/grar5WOKAZQONp5Tog+KdraCIULik4YSDcb3e6LQwhdP8Vhs7yZY=,iv:exFQPbdCvMmHGnFU40WHHqiYSL/WSFM4iwezcZYkBq0=,tag:qfwWoXZAEPSgsFqOuHB/Qw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
