# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:J6noXXtiGPyNx6s4vzVkQPyQIbGdBHpj0/hzuYsrEw/W0NItTzbSYzpXPDfz09VrkEt2DpUHvtAAwFwVnXujD/8YcAvRpumsys/av7HLm3NBmqRvta/7wDlLUK/9ul3Q++DtsxzNv5ciTuBVLuzsSk8t+bafDE5TnH5D/3Dh8oXxZ6Wj9zfqlP1wbQbofumXo1phd9cCBw6mlKvNuU7RE3SJploPLQPr/h2uMNO39Q==,iv:zFFqaSjMdfY8Z6wNGzq4TFhWVX6GUlVPuWtH62CEe/g=,tag:EnDIrLHkEqXv+1sa7u5dvg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRmJxanQ3U0tOa3hLYzg2
        YTBEajdRQUlzNFhkUkJWWGI1WEdOYlNlUWlrCnZRZ2x3V1ZPc0g1dUxHOU5DbWpm
        ZFZKWDc4SzlPWHp5Q09BUkxGUWZRdW8KLS0tIG1NZk9wU01HQUFoMjBPeWtUdndw
        WHFxR0RUbEViNFpZeE9TenIrdVNOQlUKHgiy+3A4Uwi/1sKKBXIBAOTIr1OGjzzh
        l4CnTSCa2AlnPcUusnWcQupVbldBFwX40X8Jn2USr8Jsbzt+BsJDlw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-08T23:09:14Z"
  mac: ENC[AES256_GCM,data:WgqQYXVNNf/Xn3Ob61eyoYMzdrcrV6z9NiCop9bSyaqNmefUcQUz0pCU9QkxMEFLjjJDAONjPRualBKo2aE874qJzkQAtv70tFPRI0vtpaVQ/BaaI75XkqXtzMQy3hW2e0+VInWkkaOnu8Wd0WHxpGbTE5z73dgiGGYSRkIHZ9A=,iv:NFzGPlrHwFhqBU7Ta+rM9IMFlg2ysnFELn7j6idMaps=,tag:Zi8YUNUoxFyxxiMIEWKvSQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
