[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
BOOTSTRAP_DIR = "{{config_root}}/bootstrap"
KUBERNETES_DIR = "{{config_root}}/kubernetes"
ROOT_DIR = "{{config_root}}"
SCRIPTS_DIR = "{{config_root}}/scripts"
TALOS_DIR = "{{config_root}}/talos"

[tasks.deps]
description = "Install Python dependencies"
run = "uv pip install -r requirements.txt"

[tools]
python = "3.13"
uv = "0.7.16"
"aqua:budimanjojo/talhelper" = "3.0.29"
"aqua:cli/cli" = "2.76.1"
"aqua:cloudflare/cloudflared" = "2025.6.1"
"aqua:cue-lang/cue" = "0.13.2"
"aqua:FiloSottile/age" = "1.2.1"
"aqua:fluxcd/flux2" = "2.6.4"
"aqua:getsops/sops" = "3.10.2"
"aqua:go-task/task" = "3.44.1"
"aqua:helm/helm" = "3.18.3"
"aqua:helmfile/helmfile" = "1.1.3"
"aqua:jqlang/jq" = "1.8.0"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.47.1"
"aqua:siderolabs/talos" = "1.10.4"
"aqua:yannh/kubeconform" = "0.7.0"
