---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: n8n-backup
  namespace: default
spec:
  sourcePVC: n8n
  trigger:
    schedule: "0 * * * *"  # hourly backup
  restic:
    repository: n8n-restic-secret
    copyMethod: Snapshot
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    pruneIntervalDays: 7
