# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:TcsbzEUeb8sENj5rf6Nc7eLRO0DAknSsiqiMdhVDml/24HJi8AEFmg==,iv:QW9l/uejSE/Yp/5m2nz6EN2a9LvzIbbYQYS+YqPNx/I=,tag:OV1JgTo5WIDtlJIWngG6aA==,type:str]
sops:
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcGR6Mnh6eUhvUGg2R2hO
        ZFY1NXJrNVFmWlJFa3FTSWpKWWFCVk1UY2dBClU4ZW9DK1lRSU5VMnlvUk1LNzZ5
        T251ZXAxanlmOTJ3RXdGeHlLTVB3Z2sKLS0tICtEbFExRlV5cU1HK1hNTHh1MDJG
        UmhYNmVmVWxjVU52N3ZxYkJseUxibVkKHx+Fbpp0zsjLHG4IW1PPVyffpg/2ZIgF
        1fn+5tRU9jYMzgOWMq1LoX0xl/anvdl78AYWqoBeE/dGp10xqt5j9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-14T15:02:38Z"
  mac: ENC[AES256_GCM,data:vuxUIOcHqi7GVba/HMqbUrzH702WwRXB0uHZZPAW7r6WlBsV+loA7eFBzvP0JHJmeBJvapzdOREBvNQkkRMRB/lh8eoAvost9fi48xXkfDzLkZo3ENrW4lJaCXG28EDtdxFaBJip1U2rBM59uaG+j/OlKSguTo2duCEEfi7o0Qg=,iv:yDK9Lay9atYQvGl9gwdcxzlx1H5ufO7ep1UYjOM0LLE=,tag:3wOKi+NGf76T+YhgLKCm4Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
