# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3eM/5NnKWHaztJOpJhGTpB6ryqK6Y7WmuNJOsi9DUBQ7HxehyTzUqQ==,iv:oFDl8VL1Y3gPLlYLrwmxLIwbXqm7wlmUPwRVopHP/dg=,tag:O5/nngD+s+xS4orksa6DsQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURWM2bHlpRzVSNmlMVCtk
        NWhuS0NQelVjN3lKbFJvWWNlWW9XRkRYK1NnCjJ1WXFpVUJMcE9HL2JLajI4U0Vo
        Z3kxMG1pQ3FQUGZNeEl2RXVhN0pnRTgKLS0tIFpyZ1ZsQ1dCQnhjanF6a2NOcnUx
        TnhFRFlNR2N6QW5UZFloVzRZL3IwRUUKGMmwdTKIFYo2eHziM+2fSERfVvyvgA0o
        GIbyviczhgJFusU53hnAlsXJf7DH8nucZQQomHLiWE8ERNliRo1N6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-12T20:13:17Z"
  mac: ENC[AES256_GCM,data:iVpnFItan37Z0uVmx9FQsL8pZJtumMDLYoswptm0meZ/OUWydv4q99GRsCBQ0z8j4IxmwmXSTFMdiNRQjcAdLumRpQ76w3hF1MvO+3oBX7R6kYuD6oWWUAzxEwBZarQFShHw+vhoZ02Wyw0zHv49SU4VStgNQyoijSM8vjsiC0E=,iv:XoYqkrSPFWvnB7ZxVcf/6nAldqAKnBhb/y/9rMP7/y4=,tag:0XFJRv0ZT1wlvWP0s9i8YQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
