# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-secret
stringData:
  mediawikiUser: ENC[AES256_GCM,data:t89zPv4=,iv:/ExB4nhlo2wjBLnYaubhPEWkIzBxxs0809QH2CzewTc=,tag:MvDbXlfAE8FzNYlYoYsGLw==,type:str]
  mediawikiPassword: ENC[AES256_GCM,data:Hc3BB675sDiSvQ==,iv:pS+Wgjvi2GyfWvbiC8NVPKU0JHTfRSx75M6fVUfSSRY=,tag:JmyhC/dsBGBkF4Cqf6VkNA==,type:str]
  mediawikiEmail: ENC[AES256_GCM,data:OjPpA9FZyj2Zg6L5qLL4vVKB,iv:WPJe0bsYOb33w728QBVY/HWNzpaJP6gE0LQuQX2I9zA=,tag:1stWhooWieyWsl2yXCNQRA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aFhkT29vQm9XVEFZMlpp
        Ung1Y1BKZVZiTmx6d1lobDJOV2VHMDdSSERFCkdyYzlMZHZjMlBEajZ0a3hMUFFN
        UGk3RjdPWm1NeU9HTUIwRWdXQ3dmS28KLS0tIEdWS0p2WFJpdlBjbVdYUEtRVXBm
        cHBBam1NcVlNeFBMNk5zdE1Rd3ZabDQKsIlH+lqB8kgxC/2Qp2GxMoehOk5lffpQ
        qGJoxsB7s7bRWmj7cJX33b0fU2UTlZFnXcsF/v5UZwCkkx2m8Pozpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-21T11:02:35Z"
  mac: ENC[AES256_GCM,data:Ev0xJadbt6jl7MYsoQoCwKLtgtuKWPCyTVqtZsdZRpHb8B8XazvUPw9UCGnlm+T6LONXfxLecYKysEulsRKK5Us+XAO/qKJsSroT2R/o+whd4PkT5n3tYdtl7vGbyBrBjtPomod6U98u6UDK8/0YmDscF06DC19/6nL9sEthtvU=,iv:OD+SutUr7ICbWa14F7CAahSY8MvELD3vAmFih86OPN8=,tag:byhoyAINMXpwR547anDQzg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
