---
authentik:
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: internal
        enabled: true
        hosts:
            - authentik.endsys.cloud

postgresql:
    enabled: true
    persistence:
        enabled: true

redis:
    enabled: true