# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CyNHGrjOTjQEuBpVriMDbcsCiWDhnDhxTVUQLn5QWIY=,iv:6MCBzAuG3DFS8LYHYG0PpbgvBTnuskHqOxVwXUd9x7w=,tag:ZmpFgcmivHnMMuEwY27KaQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbTRVclNNeTd6UE0zcUtN
        R25tN0V2djkweWpzem1jc29jU0VrSStIYjFnCmwra3hmVFBqKytGdXdpb1o1TXBu
        UmFiRktlZlVMcUhjVDgyZmVybUxvN0EKLS0tIEhBQXhaVlU1V2JRTTduZ0FEYnQ2
        U0N3NjhzSHYzYm51aUR4ZVBuQlJLckEKHdOSCv2AYiUvAerBgmOaQzQ68/gdK3b7
        gjlp/LYwpH+yoZ8qB1cuyAXNRbSF2sOOfGdImsF8e7vZwDpr9rMSmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-28T15:39:49Z"
  mac: ENC[AES256_GCM,data:/rNkbrE/48x60ma8tD3IpFOIKjvhgckaLnbbTEeaqekSD4sMVXGFukKWiLGOWFcFZTXF8pjxQfjZ2nL4korxXOWTYsqrrVA1N0+Tpok15hP/JomHtSHvu0meJHXcAgyMEtQORDupxoaRK4/Qxi49fa+iXD9Zfwxg/dxyf6zAxBU=,iv:0pK0hVeBLxynQyDUJK+wbV8ByFSFiVkOc3Pk3O051kg=,tag:7eQJhFT4D5bTMzxvjqVB3A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
