---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 1h
  chart:
    spec:
      chart: bitnami
      sourceRef:
        kind: HelmRepository
        name: wordpress
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflared
      namespace: network
  values:
    wordpressBlogName: Jessica
    wordpressPassword: testing123
    wordpressUsername: sean
    persistance:
      size: 10G
    service:
      app:
        controller: wordpress
        ports:
          http:
            port: 80
    mariadb:
      enabled: true
      primary:
        persistence:
          size: 10G
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
