apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:jW/OhlOLXjKLZh90,iv:nOFjKtSd2uMjr3fCMXs70J0l4lkT+4TCZ+DutnbY/j4=,tag:/4iEfYO150hgWKid7SFF9Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc2FKbkVKdnlDR2hvSHpF
        VUY1TFh0QUE3bXpPQmxSOTZrQXhlL1o0RzNnCm1pNFNLeUVKNXBSSU5IeWFibHEv
        TlZQa2JxRnllZ25kUTdBTlBTQzZWMXMKLS0tIE9jVm9JSmRlTTdPRzNCcFBreEpa
        VlRMUjk5aDJrbU9uaDlTL2JxVEsyS1EKg2FQrlhimEzMjdw2vE8G+KBHU3sOfXOM
        DfikeUU3AJU37vdtJKWOtl0se/aJAqNcWAYbTg/GVG9apUhZlVpCYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-28T15:39:49Z"
  mac: ENC[AES256_GCM,data:teYdHeLiKRJHNtqWjcDh+swNNuY2H+YP355YiZPu4O+YprBeR3c3XpgUGdy3ZM+AP7ammoP+IH0OEIkaWql2gHMTbtvIp6nyp2hwTqp8m1elyYeQd+lDCl6S3CU4KrXoZaNq4nLU++/mdq1GuOjV6NIn6jyPAThESbODvpdNcDw=,iv:7uVwM/3acGVKVX2FXknIqdKQyurJmxYOaY8hyr88A6o=,tag:M+8sgJJ03o84sZetAj/3Yg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
