apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:rGgP1Ss3BslQ5r8mYT53kGc2h5Dw+UJKWP+WrBq92Nx12nRBTs1Le2jldwoeSaCOSmjKYrvHvapTvENMV2RfQJp1xWQuTUaW9Rs=,iv:muR5oH+TOSilesEuNH/YCD3iyaOPD//ZUyULGWtZQcw=,tag:5hXdPC1GFIX8NDlpa8muQQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVGpRYTZQd2twT095ckE0
        UU8zbjhSczVNUW00a0loUjYyaXczekczSVhvCkJidWk3TTZWZ2kwR3JxWG9vbFFG
        eFhQYmc3STZSR05EUW5Tc0dGUkFEOW8KLS0tIHR2Sld0a0VRdTFhVElmZUl6bmRo
        WDVabFZ1cVd0dGtuNlE5TVlwd3BUNmcKhnwJq/grLVVTL93lx9pAf73CyC2LHma7
        1Gr7OfaqQ6YJghmxLBrTuNN2AEZ1rqpJyG8xfKWjBZOTpYMzhrPm7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-08T23:09:14Z"
  mac: ENC[AES256_GCM,data:2WY6ek1oIiLB/erNobSMvhBXCeWLfG7ESNO3I8tTsSrvHObImOmXrbYF0vye6/WkFNCcuC4e0RzjYoYMsMS3l0k4Jb4kPLMqZvurADicZ+CO1o2rseNInILELtEwHIi6gsFOU79R0a8/zN6jc9iuvGTKAuFWil4kod8dmF+CbV0=,iv:iPCQoAnJWE2/mlBZOI33U7NHtYPdKywrQ43LN8XS9Lc=,tag:Uo0e30/owd5xQpFslBYxtA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
