# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uQEEjOkydb0w4YE1k7PFwsSvjO8oN8H5lRSxH5nleRBctduzUI3v+w==,iv:pLqWEy0xIhtDeESbYuu9bFai1zPts57hu248Nyc8+EI=,tag:WJs7CNa6YgLao2Ws8ewUHQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Qno3SVpWQ3BnMG5TNlFE
        Qkh5L1NUbitFM0o3Qm5na1FEdkQvSVpXMnhvCm9uNzlpRWJHc055TkppMVdXTk1i
        WjhPNk8vODlhZjd6YnJaWWVqdU9XV2sKLS0tIEdiU0M3MzB1M1prWmUyMjlqamRm
        cXovOVhaT0IxL24zcWtHU3FIK1VkcWsKGkcbC07XFsw0DmzmZ4uL7J4XkNFx1KAG
        AtZeWDHcVr0q+mszcxK0gtszHIWF4vkxYXFq+2ITWEQ0rvhBfn52OQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-13T16:08:56Z"
  mac: ENC[AES256_GCM,data:bV57BO4naIF/UrkR/LV/TyzpwkTzP4dDWd7j2iHHS9AQ+crhvo9KTpi4KZo6v6lsGcPG9fHukTfmOFzR/38q4q2a5PPup4/I7SdG2PsSuRMDB59OCKruhsP+UdeYZS4zefmUduhhJ7BLV8oGrxf4D1I2cP280Or5mGwzzU5hV4g=,iv:n5x9+cQ9Zup99wJism2/sOWfyj34Jqhkj+zaQ4Nye0s=,tag:aVU67cvFP7YUM6FHGQqFww==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
