# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app n8n
#   namespace: &namespace default
# spec:
#   # dependsOn:
#   #   - name: n8n-postgres
#   #     namespace: default
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   interval: 1h
#   path: ./kubernetes/apps/default/n8n/app
#   prune: true
#   retryInterval: 2m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: *namespace
#   timeout: 5m
#   wait: false
