# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.10.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.33.1

clusterName: kubernetes
endpoint: https://10.0.0.40:6443

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.0.40"
additionalMachineCertSans: *sans

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "kube1"
    ipAddress: "10.0.0.41"
    installDiskSelector:
      wwid: "naa.500253885012c985"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "90:e2:ba:1d:23:f0"
        dhcp: false
        addresses:
          - "10.0.0.41/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 9000
        vip:
          ip: "10.0.0.40"
  - hostname: "kube2"
    ipAddress: "10.0.0.42"
    installDiskSelector:
      wwid: "naa.500253885012cc07"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "a0:36:9f:a4:06:d8"
        dhcp: false
        addresses:
          - "10.0.0.42/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 9000
        vip:
          ip: "10.0.0.40"
  - hostname: "kube3"
    ipAddress: "10.0.0.43"
    installDiskSelector:
      wwid: "naa.50025385002046dc"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "a0:36:9f:6e:bc:14"
        dhcp: false
        addresses:
          - "10.0.0.43/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.0.1"
        mtu: 9000
        vip:
          ip: "10.0.0.40"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

