# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  values.yaml: ENC[AES256_GCM,data:mKgWAkDv+N1/PIv1E+1Re0cdW0krmyZEjyczowU2tOjzOoEn1AxYCZKkdfzHkKn1/b07g6gv6zXJZkXPJQ+zo63/RosTVUC+KVdQmQLflkJBpvxWSrqtNWOkOQqZqVg/68MFtVDfKc7oGI4qXX36/uO+Vr0FOhYJmPVMN8DN+2XG99q5QefdjZ9XhTSrqf0v7SpqpdmB07FCUQzVqI43ICaBJfx0YcxLJKoCW2ru0GxwpfdXd/DhHujHMw/I9VyzKdhN7q4yVwZn438umOeTocWrmcSKnjtZt/7nciM4Gjc85V9alh9uzHRh3eGr2nbAMSePuqr4LL3BEfQV6FcpvHwHjdvCGDSEYQEbLjyxE7R1o1T1os7dHeLNFthJ4pWpl/6Fg6T4FxzOtETq85uxStJuVWnVFk+vM69F64bx4rhrGKJ4ljJbfOxtuTYRNY8=,iv:aCuudgtj4v/ZjHuliuEFhKJ3rtu3ZnAuOxjxrwPjpl8=,tag:pUW1mKKO66ncv7YyKWCObA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WC84SGtIQXM2K3VqOUtm
        YVl6ckJqekZacktvRFdFUXEyVEQyc3RrMlRrCkY2TGluV3RzK2s4dXlEcU5ocEE3
        ZFp2UGU0bW0xQ1pQZnhSWUVET1laakUKLS0tIFQyRGdsbDJvWTNkOElGQ3g1N05m
        T1phQnZwN0h0NGllSjUrYkY1Y0tqU3cKryrN4CoHD0xcn3XknU6yibKU3uOsSZm2
        xEZK+vrXZN7Ti2v2JYH3FcZQw0fN+q6DC4aeyuPccZS/yupI52uTVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-11T09:47:53Z"
  mac: ENC[AES256_GCM,data:yNzjhyTOOxMI5p17wmcINyMKJ2gVGja6uiUFbd2ANYtIpE/Hn7tW+60TaXqJf6Yudf0FFfrouvBBb4/rZNwjGMifKkZJtLXqRKWdmmRhEDbwiu1qF8Zc/nOoXiAMkM8xnPa0G7y9mrolo6NBMeRY0qDEQUZaHp9ScyotUI2S8hg=,iv:U+gAVQ2cf83mO0l7lCwchhyIk9IQJia5ca7AfxYvoGg=,tag:R841gpY3vd/erYN5dDEQsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
