---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otterwiki
spec:
  interval: 1h
  chart:
    spec:
      chart: otterwiki
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: otterwiki
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflared
      namespace: network
  values:
    image:
      repository: redimp/otterwiki
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "2.13"

    ingress:
      enabled: true
      className: internal
      annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
      hosts:
        - host: wiki.endsys.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific

    persistence:
      enabled: true
      size: 5Gi