---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n
components:
  - ../../components/common
resources: []
  # - ./n8n/ks.yaml
