# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: bw-auth-token
data:
  token: ENC[AES256_GCM,data:+4VKPPXVxtoPLlbCCyQeQUajOVjTgEj2dDiOlTxzMKN9PNYyBc67UsFKQfBQak0ZznYY+scYiLWOLD/xjDpAej1PFXMpecwRs9SO6kbWdIv85fld+TDXSuqTGKRSdQ==,iv:Uur9h13u7LnjAYQkTkmevtoKZRPu6H9N/GZIHXwi73o=,tag:07hYb2AbcTGX/xq01Cj1Lw==,type:str]
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19ej0wrqwksvmgl6kjmyc6504sfn9gs8luns742wlgjwulcrjscfsd2sf2z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WC84SGtIQXM2K3VqOUtm
        YVl6ckJqekZacktvRFdFUXEyVEQyc3RrMlRrCkY2TGluV3RzK2s4dXlEcU5ocEE3
        ZFp2UGU0bW0xQ1pQZnhSWUVET1laakUKLS0tIFQyRGdsbDJvWTNkOElGQ3g1N05m
        T1phQnZwN0h0NGllSjUrYkY1Y0tqU3cKryrN4CoHD0xcn3XknU6yibKU3uOsSZm2
        xEZK+vrXZN7Ti2v2JYH3FcZQw0fN+q6DC4aeyuPccZS/yupI52uTVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-06T15:13:05Z"
  mac: ENC[AES256_GCM,data:2HE/Y9zPaBOS2xdkIqAu2JP+bXEir8GdADR2c+g5WsLY/MGvJ/2KMSq39HtrOIuhz/jyaW3J6mXb4+czZpq1ZB7Zx9dAH/5jUpDNC3NGr2gYfdUQvbPx1QogqWJ+Sie2pNW1cj6xhenE3oJ76+hOytAzGj9CDl7r3BGzlywOs/c=,iv:olq8Njt8O4e8sGbcicy1kJMyDtQNKUbQqdP4O8poshc=,tag:DjIWhT+eAjma1aC1jpvx8Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
