---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pelican-backup-data
  namespace: default
spec:
  sourcePVC: pelican-data
  transport: rsync
  schedule:
    - daily
  # restic:
  #   repository: pelican-data-restic-secret
  #   copyMethod: Snapshot
  #   storageClassName: nfs-csi
  #   accessModes: ["ReadWriteMany"]
  #   capacity: 100Gi
  #   pruneIntervalDays: 7
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pelican-backup-logs
  namespace: default
spec:
  sourcePVC: pelican-logs
  transport: rsync
  schedule:
    - daily
  # restic:
  #   repository: pelican-logs-restic-secret
  #   copyMethod: Snapshot
  #   storageClassName: nfs-csi
  #   accessModes: ["ReadWriteMany"]
  #   capacity: 100Gi
  #   pruneIntervalDays: 7