---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: pelican-data-restore
  namespace: default
spec:
  trigger:
    manual: restore-001
  restic:
    repository: pelican-data-restic-secret
    copyMethod: Snapshot
    destinationPVC: pelican-data-restored-pvc
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: pelican-logs-restore
  namespace: default
spec:
  trigger:
    manual: restore-001
  restic:
    repository: pelican-logs-restic-secret
    copyMethod: Snapshot
    destinationPVC: pelican-logs-restored-pvc
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi