---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/mutatingadmissionpolicybinding-admissionregistration-v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: volsync-mover-jitter
spec:
  policyName: volsync-mover-jitter
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/mutatingadmissionpolicy-admissionregistration-v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-jitter
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: has(object.metadata.name) && object.metadata.name.startsWith("volsync-src-")
    - name: has-volsync-created-by-labels
      expression: object.metadata.labels["app.kubernetes.io/created-by"] == "volsync"
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          [
            {
              "op": "add",
              "path": "/spec/template/spec/initContainers",
              "value": []
            },
            {
              "op": "add",
              "path": "/spec/template/spec/initContainers/-",
              "value": {
                "name": "jitter",
                "image": "docker.io/library/busybox:latest",
                "imagePullPolicy": "IfNotPresent",
                "command": ["sh", "-c", "sleep $(shuf -i 0-60 -n 1)"]
              }
            }
          ]
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/mutatingadmissionpolicybinding-admissionregistration-v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: volsync-mover-nfs
spec:
  policyName: volsync-mover-nfs
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.32.0/mutatingadmissionpolicy-admissionregistration-v1alpha1.json
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-nfs
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: has(object.metadata.name) && object.metadata.name.startsWith("volsync-")
    - name: has-volsync-created-by-labels
      expression: object.metadata.labels["app.kubernetes.io/created-by"] == "volsync"
    - name: repository-volume-does-not-exist
      expression: !(object.spec.template.spec.volumes.map(v, v.name).contains("repository"))
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          [
            {
              "op": "add",
              "path": "/spec/template/spec/containers/0/volumeMounts/-",
              "value": {
                "name": "repository",
                "mountPath": "/repository"
              }
            },
            {
              "op": "add",
              "path": "/spec/template/spec/volumes/-",
              "value": {
                "name": "repository",
                "nfs": {
                  "server": "vault.lab.endsys.cloud",
                  "path": "/mnt/data0/kubernetes"
                }
              }
            }
          ]