---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-nfs-backup
  namespace: volsync-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1000Gi