---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pelican-backup-data
  namespace: volsync-system
spec:
  sourcePVC: pelican-data
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: nfs-restic-repo
    copyMethod: Snapshot
    pruneIntervalDays: 7
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pelican-backup-logs
  namespace: volsync-system
spec:
  sourcePVC: pelican-logs
  trigger:
    schedule: "5 * * * *"
  restic:
    repository: nfs-restic-repo
    copyMethod: Snapshot
    pruneIntervalDays: 7